### ISSUE TITLE
Tokens don't stay in the Patrol Zone

### ISSUE THREAD

**Issue by brunocalado** [theripper93/Patrol#1]
AMAZING WORK!!!

When I create a Patrol zone and add tokens to it. They wonder to outside of it.

![image](https://user-images.githubusercontent.com/4999783/120342840-8b3cc800-c2ce-11eb-830c-89b16cb3e363.png)

**Comment by brunocalado** [comment]
my mistake

**Comment by theripper93** [comment]
polygons :P
