### ISSUE TITLE
Enhancement - Alternate patrol sets

### ISSUE THREAD

**Issue by C-Norton** [theripper93/Patrol#10]
I am preparing a stealth mission for my players. They will have a choice of what time of day they will go into the facility that they are trying to infiltrate. I would love the option for different times of day being able to provide different patrol routes. Ways I could see this being implemented would be either interfacing with a time of day add on (seems like a pain), or, more realistically, having a "patrol sets" menu, wherein you can group patrols into different sets that are active at a time. For instance, a token could be set up to, no matter the set, always do the same patrol, or switch its patrol based on sets. That way, once everything is set up with the various routes, I can, as a GM, in only a few clicks to change which patrol set is active, change how all the different tokens on the map are patroling.

Another use case for this might be in a mission where the guards of an area might go onto higher alert on a failed stealth check, but not loud immediately, and, if the "I might have seen something" signal goes out, the patrol routes switch up on the PCs midway through

**Comment by theripper93** [comment]
this is so specific that i would never implement it honestly, it's more of a macro to set\unset flags and rename drawings. Sorry but the time that would take is not worth the 2 users that would benefit from it. The macro polo channel in the foundry discord can surely help you to set this up
