### ISSUE TITLE
Tokens come back on visited tiles with smooth movement

### ISSUE THREAD

**Issue by yogiteck** [theripper93/Patrol#11]
Tokens come back on visited tiles with smooth movement. I've spotted an issue with the array that stores the visited locations. The first stored coordinates are fine but the second are not aligned with the grid anymore. Example : 
1500, 1500
1570, 1500
1501.30548, 1500
It's as if the new location was calculated when the movement is not finished yet. And indeed, tokens are not aligned anymore with the grid on the map !
I've seen another issue and I don't know if it's related to this one but it might be.  With smooth movement activated, lights don't move with the moving token  (ex torch).

**Comment by theripper93** [comment]
pushed a fix to fixup the position if they are off grid, it should adjust the positions correctly and fix th issue

**Comment by yogiteck** [comment]
The issue is fixed : tokens now snap to the grid and light is moving with tokens. But there is a new issue. Tokens can move through walls (only with smooth movement).

**Comment by theripper93** [comment]
well fuck me (are you using it with levels\wall height perhaps?)

**Comment by theripper93** [comment]
just tested and i don't seem to be having that issue

**Comment by yogiteck** [comment]
I don't use wall height on the map I'm testing. And anyway, it works fine when I don't use smotth movement. Do you want to connect to my game to se how it behaves ?

**Comment by yogiteck** [comment]
I mean token can't move through "Patrol" areas but they can move through walls (like standard walls).

**Comment by yogiteck** [comment]
https://user-images.githubusercontent.com/87486705/126215132-532033cc-b2ee-4209-b63a-5f0d39c041a0.mp4


https://user-images.githubusercontent.com/87486705/126215137-c2c59324-ce9b-4e7a-930f-1879a905c8d5.mp4

**Comment by yogiteck** [comment]
https://user-images.githubusercontent.com/87486705/126215265-e3a6f562-28ed-40bc-97d2-1bde3050febd.mp4


https://user-images.githubusercontent.com/87486705/126215267-efff5d26-834d-441a-885a-f8f98fe6023d.mp4

**Comment by yogiteck** [comment]
https://user-images.githubusercontent.com/87486705/126215371-30ca645c-5f3e-423c-9685-703ff0b69a64.mp4


https://user-images.githubusercontent.com/87486705/126215374-9e78f24b-d0b2-46f6-9be4-a229790a5133.mp4

**Comment by theripper93** [comment]
try with the new update

**Comment by yogiteck** [comment]
Yesss ! Tokens are now snapped to the grid. They don't cross walls. Light is moving when they move. The only remaining issue is when they start a new cycle (ie. they don't have any valid position left to visit and the history is cleared to make sure they can move again). On their first first move on a new cycle, tokens sometimes come back on their starting position (see first video). Something must go wrong with the first position.

**Comment by yogiteck** [comment]
By the way, I wanted to tell you that you did a very good job ! Your module is awesome ! Thanks for your help and your dedication !

**Comment by theripper93** [comment]
should be fixed
