### ISSUE TITLE
I did not get the Patrol to work properly

### ISSUE THREAD

**Issue by Ulvtand** [theripper93/Patrol#12]
I did not get the Patrol to work properly. The token moves as it should, but it does not detect the players. I have drawn a polygon and also some walls. 
Do you have any advice?

**Comment by theripper93** [comment]
the token needs a sight range to detect players

**Comment by Ulvtand** [comment]
It has it and it exceeds the distance between tokens

**Comment by Pantong51** [comment]
Yeah the patrol part does not work. Wanders randomly, outside of the Patrol area

**Comment by theripper93** [comment]
These are 2 separate issues. @Pantong51 Can you share the configuration of your token that is not working?
@Ulvtand If you system is not dnd5e the player detection might not work

**Comment by Ulvtand** [comment]
So you mean Patrol is only made for 5E? There is nothing about it in the description.

**Comment by theripper93** [comment]
> So you mean Patrol is only made for 5E? There is nothing about it in the description.

Patrol is not made for 5e, but many system don't use a standardized way to identify pcs vs npcs, so the player detection will only work on some system but i dont' have the time to test all of them. i added a warning in the repo that the player detection might not work outside of 5E

**Comment by theripper93** [comment]
@Ulvtand i published an update that could improve system compatibility - try that and let me know

**Comment by Ulvtand** [comment]
> Patrol is not made for 5e, but many system don't use a standardized way to identify pcs vs npcs, so the player detection will only work on some system but i dont' have the time to test all of them. i added a warning in the repo that the player detection might not work outside of 5E


I remember it since you helped me in another system. If I find that Patrul does not work in a system I use, I first turn to the developer of that system and ask them to make that system compatible with Patrol. :)

**Comment by Ulvtand** [comment]
> @Ulvtand i published an update that could improve system compatibility - try that and let me know

In Witcher, Patrol works flawlessly. I have not tested Path but do not see why it would not work. Beautiful work with path. 😄

**Comment by Pantong51** [comment]
I will ask the pathfinder devs to make it work with patrol

**Comment by theripper93** [comment]
> 

I think you are misunderstanding here. I’m saying the player spotting part might not work with your system. Everything else should work fine. Again post the token configuration

**Comment by Pantong51** [comment]
> These are 2 separate issues. @Pantong51 Can you share the configuration of your token that is not working? @Ulvtand If you system is not dnd5e the player detection might not work

Sorry for the delay. The issue i'm having is that when i place an area and add patrol area to randomly move in, the NPC won't stay within the bounds. Since it's been so long and there has been an update. I'll attempt with the new version and see if i can repeat the issues.

**Comment by theripper93** [comment]
Sure, make sure to share the token configuration as well

**Comment by Pantong51** [comment]
![image](https://user-images.githubusercontent.com/7275418/146059213-9e5ced02-2e05-4d88-8a7a-e618b9edfb0d.png)
This worked the first run this time. No issue anymore. Not sure why the previous mob had issues. If i have issues again in the future I'll make a new issue following rules descriped

**Comment by theripper93** [comment]
good! hope it keeps working :D

**Comment by Pantong51** [comment]
![image](https://user-images.githubusercontent.com/7275418/146061636-463a027c-5954-4a3b-83c9-be8a9f34f0cc.png)
Sadly After some time and changes to the size it got upset. I'll create a proper ticket after work

**Comment by theripper93** [comment]
mmm, i'll see if i can do some extensive testing, but it seems so hard to reproduce that i'm not sure i can spot where things are going wrong. When you get the time, can you include a scene export?
