### ISSUE TITLE
Instant spotting

### ISSUE THREAD

**Issue by moritz121** [theripper93/Patrol#15]
Hello,

I seem to have encountered a problem. It might be on my side, but I've gone through your indications several times to make sure, and it persists. I've set up a patrol with one NPC (free patrol or with a rectangle drawn, same thing happens), where the NPC instantly detects my players on the map, even though he does't see them (I've selected his token to check the vision. He sees no one from his starting possition). If I deselect "Spot Player Characters" he patrols normaly as intended. I've tried different tokens, from different positions in the map. Restarting, reinstalling the module...

I would greatly appreciate it if you could look into that, and why it might happen.
Thank you in advance and have a good day.

**Comment by theripper93** [comment]
do you have global illumination?

**Comment by theripper93** [comment]
do they still get spotted even if there is a wall between them? did you test with only patrol enabled?

**Comment by moritz121** [comment]
Yeh. They get spoted from the other side of the map, walls in between and all. Y tried only patrol, and it works just fine. It's the spotting.

**Comment by theripper93** [comment]
what system are you using?

**Comment by theripper93** [comment]
then that is probably the issue, the identifier for "character" is probably different and the token is spottin himself

**Comment by moritz121** [comment]
Well, that's sad. But thanks a bunch for your time though.

**Comment by theripper93** [comment]
you can fix it yoursefl if you want, come in the discord and i'll guide you in the voice channel

**Comment by moritz121** [comment]
What is the discord link?
