### ISSUE TITLE
Can't get path to work

### ISSUE THREAD

**Issue by modzy2** [theripper93/Patrol#19]
0.9.2 with foundry 0.8.8, installed this for first time and have tried to follow the example but I can't get a path to work
Only this and the two support modules are active
- created a scene
- drop a default acolyte token on it
- draw a two segment line drawing
- name it Path1 in the text box
- update position tab of the token to tick path patrol and put Path1 into the name field
- pause/unpause the game to be sure
- click the reset paths/nodes button
- click the toggle patrol button
nothing happens..

**Comment by theripper93** [comment]
should be fixed
