### ISSUE TITLE
Patrol.js line 40

### ISSUE THREAD

**Issue by Jonwh25** [theripper93/Patrol#2]
Foundry v0.8.6
dnd5e 1.3.3

Seeing the following error in the console log:
![image](https://user-images.githubusercontent.com/60674327/120398401-0ada8f00-c2ef-11eb-856e-d36ae674ed15.png)

**Comment by theripper93** [comment]
mmm.. i'm assuming you have a token with no actor assigned for some reason

**Comment by theripper93** [comment]
should be fixed in latest update
