### ISSUE TITLE
Feature-Request: Different Paths for Day and Night

### ISSUE THREAD

**Issue by maierflo92** [theripper93/Patrol#20]
Hey,
first: awesome work you've done here. I wondered if it was possible to add a new setting where I can specify different patrol paths for a token depending on the darkness level (as with the vision limitation threshold)? I often don't know at wich time my players enter a map and for realism I often have to manually move many tokens if I planned for them to enter at night (where many are sleeping in beds) but they want to do it during the day (where many are working / patrolling / ...) or vice versa. Thanks in advance!

**Comment by theripper93** [comment]
There are no planned new features for patrol.
