### ISSUE TITLE
Random Selection of Sounds

### ISSUE THREAD

**Issue by Clashsoft** [theripper93/Patrol#25]
Could it be made possible to specify a directory containing sounds and pick one at random? Or a playlist would also do the job. It would give some variety to the sound effects.

**Comment by theripper93** [comment]
i'm afraid i'm not adding any new features to patrol, that said you could hook into the apis described in the git page to achive the effect you want quite easly

**Comment by Clashsoft** [comment]
That's unfortunate but ok. Though I don't think it's a good idea to just close issues that you can't work on - maybe someone else will make a PR if they see the open issues.

**Comment by theripper93** [comment]
it's not issues i can't work on, it's request i don't want in the module, also i'm not acepting prs ;)

**Comment by Clashsoft** [comment]
Every issue is currently closed. So you just don't want to do anything with the module. Got it.

**Comment by theripper93** [comment]
I have 40 modules , at some point I call them done. Issues are closed ether because a bug was fixed or a feature was rejected. Feel free to make your own module :)
