### ISSUE TITLE
Dead guy walking :)

### ISSUE THREAD

**Issue by BlackWand1** [theripper93/Patrol#28]
**ALL OTHER MODULES DISABLED?** (False)
**Module: Patrol, 0.9.5
**Conflicting Module (if applicable)**: 
**Foundry and System version**: 0.9 DnD3.5e 0.99.1
**OS, Hosting, Browser (if applicable)**: Windows 10, Edge Chromium
**Short Description of bug**: My dead guy (npc) started following its patrol path after combat.
**Simple steps to reproduce the bug**: 
**Screenshots and/or console errors**:

**Comment by theripper93** [comment]
The issue has been fixed - keep in mind that if you send in a report like this without any kind of information and without following the bug report instructions again you will be blocked from opening issues on my repositories
