### ISSUE TITLE
Patrol Speed should not be capped at 10 seconds

### ISSUE THREAD

**Issue by MrManlyMan** [theripper93/Patrol#29]
Hi, really like the concept, but imo there should be an option to go way beyond 10 seconds patrol speed. I would like to use patrols mostly as an atmospheric element for large city maps to bring them to life with guards patrolling walls hundreds of feet long at night. 10 seconds to traverse a distance of 150feet+ is just way too fast and gives off the impression of the guards sprinting for their lives rather than actually patrolling.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
