### ISSUE TITLE
Checkbox to turn off world pause

### ISSUE THREAD

**Issue by PhreakedoutClassic** [theripper93/Patrol#30]
First off I want to say great module.  This is more of a feature request vs a bug/issue.  I would love have a means to turn off the world pause that occurs after an NPC spots a character.  The use case I am using in my campaign is a merchant or known NPC will greet a PC once alerted to them.  This works really well other than it pauses the game.  I am a bit aware this is slightly misusing the tool, perhaps there are better ways to do this via macros, but just a thought.  Feel free to disregard this issue/request, if its not something you want to get into.  Thanks!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
