### ISSUE TITLE
Suggestion: randomization of patrol speed by token

### ISSUE THREAD

**Issue by TogaParty** [theripper93/Patrol#34]
Suggestion: randomization of patrol speed by token.  Perhaps a variation +/- defined in milliseconds or something similar in the speed a token moves when using smoothed movement.

E.G. I'm using this to simulate a busy urban environment with a lot of tokens following paths.  They tend to clump up, which wouldn't be an issue if there were a small variation in their speed.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
