### ISSUE TITLE
Option to allow patrols to continue during combat

### ISSUE THREAD

**Issue by TogaParty** [theripper93/Patrol#35]
E.G., I'm using this to create a busy urban environment with lots of tokens following paths.  It would be great if this motion could continue during combat, either smoothed or perhaps on a lair action.  Maybe defining their movement speed and having tokens advance on their patrol or route on their turn.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
