### ISSUE TITLE
Spot is not honoring "Limited Vision" walls OR not calculating based on sight, but instead movement.

### ISSUE THREAD

**Issue by galaara98** [theripper93/Patrol#36]
Walls generally have 3 modes
Normal
Limited
None

When a creature is Patrolling with "Spot" on and there is a Normal wall between the creature and the players, Spot works fine.

Limited Walls are designed to block after passing through 2 "Limited".  But Spot is going all the way across the canvas and ignoring walls if they are Limited.

take a map and make a bunch of "Bushes" (enclosed square or polygons), using walls that are set to
Movement restriction: None
Light, Sight, Sound Restriction: Limited

put PCs on one side of the bush(es), and the Patrolling w/ Spot creature on the other side.
Enable Patrol and unpause game

Creature will spot players,
     even though you can test Line of sight and it is blocked (because the polygon has at least 2 Limited Sight walls between)

**Comment by theripper93** [comment]
Interesting, it seems you found a foundry bug - as you can see i'm definatelly doing a sight check

![image](https://user-images.githubusercontent.com/1346839/165071700-fa3b34ec-7a23-4278-9ac8-10aee7530e9f.png)

And from my testing you are correct in that 2 limited walls do not prevent the spotting, i'll close this issue and report it to the foundry staff
