### ISSUE TITLE
Alert and Random Patrols Don't Respect Wall In Levels

### ISSUE THREAD

**Issue by Zaelitude** [theripper93/Patrol#38]
If you are using the Levels Module, then the patrolling tokens will both walk through walls and alert through walls built within Levels. This is particularly jarring in the PF2e system where most vision types do not have max ranges, so the patrolling tokens would alert from the other side of the map through the walls of several buildings.

**Comment by theripper93** [comment]
Levels compatibility is already a feature request added through the proper channel, im unsure if/when it will be added

Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
