### ISSUE TITLE
It's not working with SWADE 

### ISSUE THREAD

**Issue by brunocalado** [theripper93/Patrol#4]
It's working fine in DnD.

But, I can't make it work in swade. I can't turn the patrol button on.

https://user-images.githubusercontent.com/4999783/120505678-96a9f500-c39b-11eb-8481-9815cc6357c5.mp4

**Comment by theripper93** [comment]
first, you have the token selected so it won't patrol, second you can come on discord for help so i can check it out (i'm in the foundry discord)

**Comment by theripper93** [comment]
a combat was started - issue closed
