### ISSUE TITLE
Tokens stop moving after a few seconds

### ISSUE THREAD

**Issue by MacTruck3-Code** [theripper93/Patrol#47]
Tokens bounce around briefly and then stop. Console provides the following errors:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'x')
    at nn.doPatrol [as fn] (pathPatroller.js:134:57)

FVTT: v11.313
DnD5e: v2.3.1
Patrol: 1.3.4

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
