### ISSUE TITLE
Question/inquiry

### ISSUE THREAD

**Issue by karpana** [theripper93/Patrol#48]
Is there a macro available that will flag selected tokens as being 'random patrol'?

Context: I set up a large map with all of my tokens (about 100) and forgot to set the patrol flag on the 1st token that I used for copy-pasting the others.  The number of clicks needed to set patrol for this many tokens is far too high for the value I want to garner. 

Thank you on advance

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
