### ISSUE TITLE
Not detecting PC

### ISSUE THREAD

**Issue by vampiregoat699** [theripper93/Patrol#49]
No matter the settings the patrols never spot the PC right in front of them at all

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
