### ISSUE TITLE
It don't work for player

### ISSUE THREAD

**Issue by brunocalado** [theripper93/Patrol#5]
Hi. 

The movement is not appering to the player.
The pause from Patrol is lagging.
There are lots of errors:
![image](https://user-images.githubusercontent.com/4999783/120653718-57d97500-c457-11eb-9f94-088a7229ae49.png)

https://user-images.githubusercontent.com/4999783/120653064-bb16d780-c456-11eb-9e1d-0523945a983d.mp4

**Comment by theripper93** [comment]
oh shit, i know what's happening, gonna fix it asap

**Comment by theripper93** [comment]
fixed in 0.6.2

**Comment by brunocalado** [comment]
They move now, but the player don't see the ? and the !.

![image](https://user-images.githubusercontent.com/4999783/120655422-0c27cb00-c459-11eb-8226-a07fd5120d71.png)


Patrol 0.6.2
![image](https://user-images.githubusercontent.com/4999783/120655322-f1eded00-c458-11eb-99d8-62a084e5cd61.png)

**Comment by theripper93** [comment]
Going to investigate
