### ISSUE TITLE
Not Detecting PC Tokens

### ISSUE THREAD

**Issue by mabbott093** [theripper93/Patrol#50]
Hi,
No matter how I set a creature token it does not seem to detect a PC token. I have tried every setting I can think of, even starting a fresh world with only Patrol, LibWrapper, and Socketlib enabled, still no luck. All mods, FVTT, and Pf2e are up to date.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
