### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by vanderleitelesjr** [theripper93/Patrol#6]
I think it would be better to set the patrol to stop only during an active combat and not if there is any combat simply created, if that is possible. Some DMs, me included, like to set things up before a session, as in already leaving the a combat scenario configured so we would simply have to click Begin Combat to set things rolling. More so when it comes to the Maestro module that allows you to configure a playlist to any given combat encounter beforehand so that you already have everything ready for when the players get there, but if the patrol is halted for simply having a combat created (and not only when it starts) we cannot do all this prep work and have a patrol enabled at the same time.

**Comment by theripper93** [comment]
yem that can be easly fixed, gonna have a look at it
