### ISSUE TITLE
Tile movement

### ISSUE THREAD

**Issue by vanderleitelesjr** [theripper93/Patrol#7]
I am not sure if I am doing something wrong here, but whenever a patrol is enabled the tokens will start to slide through their random patrol area instead of moving tile by tile as in your demo video. The issue is that whenever a player is spotted, any given number of patrolling creatures can be in the middle of two grid tiles, forcing me to manually move them back to the middle of a square. I know that this might still happen even if they are properly moving in 5ft intervals, but I find it to be very less likely to happen if that was the case.

**Comment by theripper93** [comment]
yes, that's the price to pay for the "smooth" movement - i could add an option to disable the smooth movement but there's not much else i can do about it

**Comment by vanderleitelesjr** [comment]
adding the option to toggle it would do wonders

**Comment by theripper93** [comment]
sure, makes sense, gonna add it together with the combat fix in a couple of hours
