### ISSUE TITLE
Feature - Stealth Check

### ISSUE THREAD

**Issue by vanderleitelesjr** [theripper93/Patrol#8]
This could use LMRTFY or Monk's Token HUD to request a stealth check from the players (via a HUD button or maybe even just a macro), the result could be stored in the token data and used to compare with a spotter's passive perception to trigger or not the actual spotting as long as the player character isn't within an automatic spotting range, if they get to close the roll is ignored and the players get instantly spotted or at least trigger the alert status.

Another way to do this is to allow these rolls to configure the alert delay, the higher the roll the longer the delay would be until the GM resets it (again via a HUD button or maybe even just a macro), but then I think the code would need to be changed to consider a delay per player as opposed to a global setting.

**Comment by theripper93** [comment]
The hooking was added so other module devs or macro makers can hook in patrol to do this kind of stuff, i'm not adding system specific features in the module itself tho
